name: Build and Deploy Go binaries

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn --cwd ./web install

      - name: Build static app
        run: yarn --cwd ./web build

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # - name: Build go binaries
      #   uses: docker://golang:1.20
      #   run: go build -o bin/medusa ./cmd/medusa/main.go

      # - name: Deploy to github releases
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ./bin/medusa
      #     tag_name: latest
      #     draft: true
      #     prerelease: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
