name: test server

on: [push]

jobs:
  test_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Create out directory
        run: mkdir web/dist && touch web/dist/index.html

      - name: run tests
        run: make server-test
